Use GITHUB_ACTION_PATH instead of github.action_path
antmicro/renode-linux-runner-action pull request #22
Opened 2023-04-25 04:40 UTC by flynneva

This is required in order to use this action within a docker container

2023-04-25 04:41 UTC, flynneva commented
Successful [example here](https://github.com/ros-drivers/usb_cam/actions/runs/4793706968/jobs/8526398937) using the action within a github action docker container strategy.  Script doesnt work yet for ubuntu 20.04, but does work for 22.04 👍🏼

2023-04-25 09:43 UTC, kbieganski requested changes
Thank you for the contribution! I left a few comments.

At some point we should add a test for containerized workflows. Although, to be honest, it's a bit silly that action maintainers have to worry about action-specific variables not always being available.

2023-04-25 09:43 UTC, kbieganski commented on action.yml
> +        sudo mkdir -p ${{ github.action_path }} &&           \
```suggestion
        sudo mkdir -p ${{ github.action_path }} &&         \
```

2023-04-25 09:43 UTC, kbieganski commented on action.yml
> +      run: cd ${GITHUB_ACTION_PATH} && mkdir -p venv-dir && python3 -m venv venv-dir
```suggestion
      run: cd $GITHUB_ACTION_PATH && mkdir -p venv-dir && python3 -m venv venv-dir
```

2023-04-25 09:43 UTC, kbieganski commented on action.yml
>          "${{ inputs.python-packages }}"                                    \
```suggestion
        cd $GITHUB_ACTION_PATH && sudo python3 action/run-in-renode.py \
        "${{ inputs.renode-run }}"                                     \
        "${{ inputs.devices }}"                                        \
        "${{ inputs.python-packages }}"                                \
```

2023-04-25 09:43 UTC, kbieganski commented on action.yml
> +          wget -q --no-verbose "$IMAGE" -O ${{ github.action_path }}/images.tar.xz;
So does `${{ github.action_path }}` work here? Or should all its occurrences be changed to `$GITHUB_ACTION_PATH`? I've not used GitHub Actions containers, but I think it should be the latter? Though I guess I shouldn't expect any GHA feature to be intuitive :)

2023-04-27 08:13 UTC, WiktorOgrodnik commented
@flynneva  I looked at the tests on your repository. The tests on jammy are probably failing because there is no bootloader, kernel and rootfs in an expected directory ./images/*. I think we need to change the `github.action_path` to `GITHUB_ACTION_PATH` everywhere, especially in the `get-images` step.

On focal there is another problem because it has Python in version 3.8.2, but parts of our type hints require at least Python 3.9 due to change PEP 585 (https://peps.python.org/pep-0585/). So you need to upgrade your Docker container to run this action properly. Perhaps we should note this requirement somewhere.

2023-04-27 13:47 UTC, WiktorOgrodnik commented
@flynneva I have fixed the rest of ${{ github.action_path }} appearances in the pull request #25 if you want to see. I think this should fix one of your issues.

2023-04-28 00:11 UTC, flynneva commented
@WiktorOgrodnik awesome stuff! I'll check it out probably over the weekend when I get a chance and report back 🙏🏼👍

2023-04-28 00:11 UTC, closed without merging